### ISSUE TITLE
JSON::PP is incorrectly indexed

### ISSUE THREAD

**Issue by rwstauner** [CPAN-API/cpan-api#125]
JSON::PP used to be part of the JSON dist (version 2.27)
but was broken out into it's own dist.

For backward compatibility JSON includes a JSON/backportPP.pm file which provides a JSON::PP package,
but it uses the "package declaration on two lines (with a comment in between)" trick to avoid being indexed.

However, trying to click on JSON::PP on the website shows me the wrong file,
and an api search by module returns only versions of the JSON dist instead of the JSON::PP dist where it now correctly lives.

**Comment by rwstauner** [comment]
I now realize that reindexing JSON upgraded "JSON-2.90" and reindexing JSON-PP upgraded "JSON-2.27" which seems weird.
I then reindexed JSON-2.90 and it said:

```
2015/02/03 17:04:02 I release: Upgrading release JSON-2.90
2015/02/03 17:04:02 I release: Downgrading release JSON-2.27
```

**Comment by rwstauner** [comment]
After reindexing both (the first time) /pod/JSON::PP went to the PP dist.
After reindexing JSON-2.90 this is still the case, so at least that seems correct.

However it still seems wrong that the JSON dist lists JSON::PP under "Modules" and links to /pod/JSON::PP (which will go to a different dist).

**Comment by rwstauner** [comment]
JSON::PP does not appear to be listed as a module in any of the JSON files (nor in release "provides"), but it is listed as "documentation" for the backportPP, so maybe the bug is now simply in how it's displayed/linked by the web repo.

**Comment by andreeap** [comment]
I noticed that JSON::PP was not listed as a module in JSON release and I didn't know how to approach this, but I will take a look at metacpan-web for solving this.

**Comment by rwstauner** [comment]
After fixing a few template bugs each dist only shows a single (appropriate) module,
and the rest of the items are under either "documentation" or "provides" and use appropriate (non-shortcut) urls.
These dists are weird, so if they display weird links I guess that's good enough.
We can leave it like this for a while and see if new issues are raised.
