### ISSUE TITLE
Lack of bug tracker JSON on various /distribution API queries

### ISSUE THREAD

**Issue by SineSwiper** [CPAN-API/cpan-api#202]
http://api.metacpan.org/v0/distribution/Moose

That returns 

    {
       "name" : "Moose"
    }

Seems pretty scarce, especially for an example on the beta docs page.  Yet:

http://api.metacpan.org/v0/distribution/DBIx-Class

Gives me more data.

http://api.metacpan.org/v0/release/Moose
http://api.metacpan.org/v0/release/DBIx-Class

Both of these have a valid bugtracker.web resource.  Is the bugtracker.mailto property on Moose throwing things off?

**Comment by ranguard** [comment]
No action in a long while, closing
