### ISSUE TITLE
Indexer fails on Pod-Loom-0.07

### ISSUE THREAD

**Issue by rwstauner** [CPAN-API/cpan-api#307]
The release displays on metacpan-web but there are no files displayed.

I attempted to reindex it and the indexer simply dies:

```
metacpan@bm-n2:~/api.metacpan.org$ ./bin/metacpan release --level debug  --latest http://cpan.metacpan.org/authors/id/C/CJ/CJM/Pod-Loom-0.07.tar.gz
2014/03/22 18:20:01 D release: Connected to "127.0.0.1:9200"
2014/03/22 18:20:01 I release: Downloading http://cpan.metacpan.org/authors/id/C/CJ/CJM/Pod-Loom-0.07.tar.gz
2014/03/22 18:20:08 D release: parsing /home/metacpan/CPAN/modules/06perms.txt
2014/03/22 18:20:10 D release: parsing /home/metacpan/CPAN/modules/02packages.details.txt.gz
2014/03/22 18:20:12 I release: Processing /home/metacpan/api.metacpan.org/bin/../var/tmp/http/authors/id/C/CJ/CJM/Pod-Loom-0.07.tar.gz
2014/03/22 18:20:12 D release: Extracting archive to filesystem
2014/03/22 18:20:12 D release: Gathering dependencies
2014/03/22 18:20:12 D release: Found 15 dependencies
2014/03/22 18:20:12 D release: Indexing 0 files
2014/03/22 18:20:12 F release: Nested processed encoding. at /usr/local/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.2/Pod/Simple/BlackBox.pm line 380.
```

Assuming that error meant there was a double `=encoding` directive i checked the dist:

```
$ ack =encod
Changes
11:     - Handle =encoding directive

lib/Pod/Loom/Parser.pm
58:      or die "Invalid =encoding $encoding at line $event->{start_line}\n";
62:    die "Conflicting =encoding directive at line $event->{start_line}\n";

lib/Pod/Loom/Template.pm
360:    $pod = "=encoding " . $encoding->encode($name) . "\n\n$pod"

lib/Pod/Loom.pm
215:other than Latin-1, it must contain an C<=encoding> directive

t/10-weave.t
310:## with =encoding Latin-1
318:=encoding Latin-1
369:=encoding utf8
387:=encoding utf8
```

The only `/^=encoding/` lines are in that test script, and technically they are in the `__DATA__` sections.

I haven't done any further investigation, but obviously if that's the issue the indexer shouldn't be dying on questionable pod in a test script.

Of course the error may mean something else entirely, but I haven't had the time to look any further yet.

**Comment by andreeap** [comment]
@rwstauner Is this still an issue? I indexed this release and I got: 

<pre><code>andreea@bm-mc-03:/home/metacpan/metacpan-api$ sudo -u metacpan sh /home/metacpan/bin/metacpan-api-carton-exec /home/metacpan/metacpan-api/bin/metacpan release http://cpan.metacpan.org/authors/id/C/CJ/CJM/Pod-Loom-0.07.tar.gz --level debug
2015/01/30 17:06:39 D release: Connected to "127.0.0.1:9200"
2015/01/30 17:06:39 I release: Downloading http://cpan.metacpan.org/authors/id/C/CJ/CJM/Pod-Loom-0.07.tar.gz
2015/01/30 17:06:41 D release: parsing /home/metacpan/CPAN/modules/06perms.txt
2015/01/30 17:06:42 D release: parsing /home/metacpan/CPAN/modules/02packages.details.txt.gz
2015/01/30 17:06:43 I release: Processing /home/metacpan/metacpan-api/bin/../var/tmp/http/authors/id/C/CJ/CJM/Pod-Loom-0.07.tar.gz
2015/01/30 17:06:43 D release: Extracting archive to filesystem
2015/01/30 17:06:43 D release: Gathering dependencies
2015/01/30 17:06:43 D release: Found 15 dependencies
2015/01/30 17:06:43 D release: Indexing 27 files
Nested processed encoding. at /opt/perl-5.18.2/lib/5.18.2/Pod/Simple/BlackBox.pm line 380.
2015/01/30 17:06:44 D release: Gathering modules
2015/01/30 17:06:44 D release: Indexing 6 modules </code></pre>
And a search within the issues brought me to this https://github.com/CPAN-API/cpan-api/issues/377.

**Comment by rwstauner** [comment]
You're right, this has been fixed.
Thanks.
