### ISSUE TITLE
YAML-Tiny Lists Two different Versions of Test::More as Dependencies

### ISSUE THREAD

**Issue by theory** [CPAN-API/cpan-api#333]
In the [release API call](http://api.metacpan.org/v0/release/YAML-Tiny). I assume this is because it appears in different sections of the [`META.json`](https://metacpan.org/source/ETHER/YAML-Tiny-1.63/META.json). But maybe it should just keep the one with the highest version?

**Comment by ranguard** [comment]
No action currently taken - closing for now
