### ISSUE TITLE
Add a 'lead_module' field to releases

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/cpan-api#376]
There are times when it's handy to know the "lead module" for a dist.

If a dist `Foo-Bar` contains the module `Foo::Bar`, then that's the lead module. If the dist doesn't contain the obvious module, then I think `lead_module` shouldn't be set (see [this gist](https://gist.github.com/neilbowers/fad7aaf15ed82e471b59) for why I think that :-)

This can all be done yourself if you have a copy of `02packages.details.txt` handy, but given that most people won't, it will make it easier for people who are dumpster-diving in CPAN.

**Comment by rwstauner** [comment]
Duplicate #149.

**Comment by neilbowers** [comment]
Doh. I did search the issues, honest, but was looking for the wrong term :-/

**Comment by rwstauner** [comment]
No problem.  Good to have more support behind a feature :-)
