### ISSUE TITLE
Pod-Simple is Gone

### ISSUE THREAD

**Issue by theory** [CPAN-API/cpan-api#377]
I released Pod-Simple v3.29 today, and now it's nowhere to be found on MetaCPAN:

* https://metacpan.org/release/Pod-Simple
* http://api.metacpan.org/v0/release/Pod-Simple

I'm pretty sure it has been visible in the past. It is [on search.cpan.org](http://search.cpan.org/dist/Pod-Simple/). Is something borked about that distribution? If so, why don't older versions show up?

**Comment by haarg** [comment]
It appears something broke when indexing the dist.  The browser for the release is [missing the lib directory](https://metacpan.org/source/DWHEELER/Pod-Simple-3.29).

**Comment by oalders** [comment]
```
015/01/14 14:04:14 I release: Downloading http://search.cpan.org/CPAN/authors/id/D/DW/DWHEELER/Pod-Simple-3.29.tar.gz
2015/01/14 14:04:24 I release: Processing /home/metacpan/metacpan-api/bin/../var/tmp/http/authors/id/D/DW/DWHEELER/Pod-Simple-3.29.tar.gz
2015/01/14 14:04:26 F release: Nested processed encoding. at /opt/perl-5.18.2/lib/5.18.2/Pod/Simple/BlackBox.pm line 380.
```

**Comment by oalders** [comment]
So, our installed Pod::Simple 3.28 does not like Pod::Simple 3.29?

**Comment by rwstauner** [comment]
Hmm...  I think we could do better than dropping the entire lib dir when
there is a pod error.  :-/

**Comment by theory** [comment]
What file is it choking on?

**Comment by theory** [comment]
Also, that error is no longer fatal in Pod::Simple v3.29.

**Comment by rose** [comment]
It's choking on t/enc-chars.t

**Comment by rwstauner** [comment]
Ugh, we don't need to be parsing pod out of t/ files.

**Comment by theory** [comment]
Well, yeah, that's the new test for that very error. If you upgrade MetaCPAN to v3.29 it will fix it.

**Comment by oalders** [comment]
@rose do you want to handle this fix?

**Comment by oalders** [comment]
And it's back.  Thanks for your help with this @theory.

**Comment by rwstauner** [comment]
a1343f066c17d66b141cd02e78a0149747bdf599

**Comment by theory** [comment]
Thanks!
