### ISSUE TITLE
csv2sqlite - Unknown Options Error

### ISSUE THREAD

**Issue by DavidBMcCoy** [CPAN-API/cpan-api#387]
Hi Everyone, 

I am attempting to run the following code which uses csv2sqlite (I need to load in a csv file, change the date formats, and output a sqlite file in a database called appy.  
#!/usr/bash

rm appy
for f in *.csv; do tail -n +2 $f >>appy; done
rm appy.sqlite
perl /Users/davidbmccoy/Perl\ Modules/App-csv2sqlite-0.004/bin/csv2sqlite -l "default_column_type = 'CHAR(255)'" -l "columns=\
[['Rank'],['Accession','INTEGER PRIMARY KEY'],['MRN'],['Dept'],['Proc'],['Priority'],['Readby'],\
['Signedby'],['Addendum'],['Read','DATE'],['Signed','DATE'],['Reason'],['Result'],['Impression'], ['dup']]" \
-l no_header=1 \
-l 'map_rows=sub{no strict; \
use 5.010; \
use feature "state"; \
use DateTime::Format::Strptime; \
state $dt=DateTime::Format::Strptime->new(pattern=>"%m/%d/%Y%t%I:%M:%S%t%p"); \
$_[0][9]=$dt->parse_datetime($_[0][9])->datetime(); \

return $_[0]; \
}' appy appy.sqlite

I keep getting the following error: 
Unknown options: default_column_type  at /Library/Perl/5.16/App/csv2sqlite.pm line 140.
}fileappycsv_optsHASH(0x7f83a986a628)columns[['Rank'],['Accession','INTEGER PRIMARY KEY'],['MRN'],['Dept'],['Proc'],['Priority'],['Readby'],['Signedby'],['Addendum'],['Read','DATE'],['Signed','DATE'],['Reason'],['Result'],['Impression'], ['dup']]default_column_type  'TEXT'no_header1sfgh-3416:~

Any help would truly be appreciated! 

Thanks

**Comment by oalders** [comment]
Hi @DavidBMcCoy.  This tracker is strictly for MetaCPAN issues.  I think your issue needs to be raised in this issue tracker: https://rt.cpan.org/Dist/Display.html?Name=App-csv2sqlite
