### ISSUE TITLE
Automatically re-index releases if they change in 02packages.details.txt

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/cpan-api#390]
MetaCPAN could identify when a release needs indexing by comparing that release's details in two different versions of 02packages. Here's a quick outline of how I think it could work.

When importing a new drop of 02packages, iterate over all releases

 * build a list of all [module,version] seen in the release
 * sort that list by module name
 * create a 'signature' for the release, by concatenating them into a string
 * if there wasn't an entry for that release in the previous 02packages, it's new so index it
 * if there *was* an entry for that release in the previous version of 02packages, compare signatures. If the signature has changed, then the release has been re-indexed by PAUSE, so MetaCPAN knows to re-index.

This should be called the HAARGOMATIC, since in a discussion in #metacpan, @haarg pointed out that the need for re-indexing could be identified off sequential drops of 02packages.

**Comment by rwstauner** [comment]
Related to #220

**Comment by ranguard** [comment]
Closing as #220 links to this ticket now
