### ISSUE TITLE
Please Test Pod-Simple 3.29_4

### ISSUE THREAD

**Issue by theory** [CPAN-API/cpan-api#391]
I've uploaded Pod-Simple 3.29_4 to CPAN. This version has a significant change: If it cannot determine the encoding of a Pod file via an `=encoding` directive or the presence of unambiguous UTF-8 bytes, it now falls back on CP-1252 instead of Latin-1. [Some details here](http://theory.pm/2015/02/11/please-test-pod-simple-3-dot-29-3/). This is because the former is a superset of the latter, so it will properly recognize more characters. But it's a test release for now so that we can make sure that doesn't cause any undue problems. Would appreciate it if you would drop it into your system to make sure it works okay for the CPAN API.

**Comment by theory** [comment]
Fixed link to details.

**Comment by oalders** [comment]
@andreeap could you do this on Weds or Thursday of this week and report back on this issue?

**Comment by andreeap** [comment]
I will take a look at this today and report back.

**Comment by theory** [comment]
FYI, turn out 3.20_4 was an empty tarball. *sigh* 3.29_5 fixes it. So please use that one. :-)

**Comment by andreeap** [comment]
I used 3.29_5 and tested the api with it, and everything seems perfectly fine. I also indexed almost 500 tarballs and there were no problems. 
@oalders if there is something else that I can try, please let me know.

**Comment by oalders** [comment]
@theory other than looking for exceptions, is there anything in particular we need to test, like some specific dists with funky Pod?

**Comment by theory** [comment]
Not really, unless you're aware of some Pod with CP1252 characters that are control characters in Latin-1. Just wanted a sanity check more than anything.

If you guys use Pod::Simple::Search, you might also want to throw 3.29_6 at it. Shouldn't affect you, but I added a bunch of stuff to try to make it smarter on case-insensitive file systems.

**Comment by oalders** [comment]
We don't currently use Pod::Simple::Search, so I think we're OK with the latest version.  Thanks for checking in with us.  :)

**Comment by theory** [comment]
Ah, okay, that makes it easy. Thanks!
