### ISSUE TITLE
Allow mixed-case text in =head1 text

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/cpan-api#396]
If you look at [Text::Diff::HTML](https://metacpan.org/pod/Text::Diff::HTML), you'll see that he's committed the **heinous sin** of mixed case in his `=head1` heading text.

It looks like as a result of this, you don't find the description section. For example, if you do a search on `Text::Diff::HTML` notice that you don't get an abstract for it.

I've filed [an issue](https://github.com/theory/text-diff-html/issues/1) on the problem dist, but maybe MetaCPAN should be a bit lax on this too?

Neil

**Comment by rwstauner** [comment]
For clarity it's: `=head1 Name` (the "NAME" is mixed case, not the pod command (I wasn't sure at first)).
I suppose I'm in favor of this, as it doesn't really seem like it would hurt.
Anyone opposed?

**Comment by oalders** [comment]
Lax is fine with me.

**Comment by rwstauner** [comment]
The API already does Pod section extraction case-insensitively.
This was actually a bug in the ui.
