### ISSUE TITLE
Add README.mkdn (and maybe README.markdown) to is_in_other_files

### ISSUE THREAD

**Issue by charsbar** [CPAN-API/cpan-api#399]
Hi. According to a minicpan, there are about 800 distributions that have README.mkdn (and 142 of them have only README.mkdn). Also, there are distributions that have README.markdown (16), and even README.mdown (5). (All of these extensions are supported by github/markup.)

I'm not sure if all of these extensions should be added to is_in_other_files (in MetaCPAN::Document::File), but I suppose .mkdn is at least popular enough.

PAUSE accepts (and copies) whatever README it finds first. search.cpan.org treats only README as a special file, but also seems to list README.whatever as other files (eg. http://search.cpan.org/dist/Gearman-JobScheduler/ )

**Comment by oalders** [comment]
This should be fixed via https://github.com/CPAN-API/metacpan-web/commit/7b9fa35b4e8ff191afbeae294cce85fee79da748
