### ISSUE TITLE
"Please come back later" error page found

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/cpan-api#401]
When visiting https://metacpan.org/pod/JSON::MaybeXS I get the multilingual blue-grey error page.

**Comment by rwstauner** [comment]
This dist provides a hash for "contributors" when it is usually an array:

```
curl 'api.metacpan.org/release/JSON-MaybeXS?fields=metadata.x_contributors'
{
   "metadata.x_contributors" : {
      "John SJ Anderson <genehack@genehack.org>" : "Karen Etheridge <ether@cpan.org>",
      "Clinton Gormley <develop@traveljury.com>" : "Graham Knop <haarg@haarg.org>",
      "Kieren Diment <diment@gmail.com>" : "Matt S Trout <mst@shadowcat.co.uk>"
   }
}
```

However, since the keys and values don't correspond, it looks to be a mistake by the releaser.
So @karenetheridge, `JSON-MaybeXS` should fix it's META,
and we need to fix our handling to ignore unexpected data.

**Comment by karenetheridge** [comment]
Ah, that's the problem! :)
And yup, I put x_contributors into a hashref, not an arrayref.. fixing now.

**Comment by karenetheridge** [comment]
I've uploaded a new release.
This release can live on as the testbed for fixing metadata parsing: https://metacpan.org/release/ETHER/JSON-MaybeXS-1.003004

**Comment by rwstauner** [comment]
Thanks!
