### ISSUE TITLE
Return more info with reverse deps search

### ISSUE THREAD

**Issue by rwstauner** [CPAN-API/cpan-api#402]
ranguard tricked me into saying

> i think we need a nested query to do the filtering, but adding the column should be easy

and then quoted me in CPAN-API/metacpan-web#1292

So I looked into it a little more...
The `/requires/distribution/$dist` ui uses the `/search/reverse_dependencies/$dist` api endpoint,
which returns a list of releases in the format of ES search results.
Unfortunately the "relationship" info is lost in the response.
It would really make things easier on the receiver side if extra information was returned.

First, the api uses a list of modules (those contained in the specified dist) to build the search results.
If the response included that list of modules, that would make searching for the relationships simpler.
Otherwise you really should be making another api call to get that list (of module names).
While the search results is in a predefined format, it's a top level hash, so there is room that we could jam in this "extra" info.  It might be worth considering if we wanted to use a generic top level key for "extra data" that we might reuse in other responses.

Additionally, we could do some relationship aggregation on the server side and return that with the result, since, if we don't, it's likely that the client will have to do it.
For each release in our search results, we could search it's list of relationships, find the relevant ones (matching one of the module names in our list), then do a "max" on the relationship phase and type
and return a summary for each release.  We could return this little hash of "phase" and "type" in with each release since each "hit" entry is a hash of "_source", "_id", etc.

Any thoughts?

**Comment by ranguard** [comment]
No thoughts... closing
