### ISSUE TITLE
Fix "immense term" exception

### ISSUE THREAD

**Issue by oalders** [CPAN-API/cpan-api#406]
```
Bulk error [index]: {"error":"IllegalArgumentException[Document contains at least one immense term in field=\"description\" (whose UTF8 encoding is longer than the max lengt
h 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[72, 84, 77, 76, 58, 58, 84, 101, 109
, 112, 108, 97, 116, 101, 58, 58, 67, 111, 109, 112, 105, 108, 101, 100, 32, 105, 115, 32, 97, 32]...', original message: bytes can be at most 32766 in length; got 38002]; n
ested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 38002]; ","_type":"file","status":500,"_index":"cpan_v1","_id":"xronuReYfnHlrI5m9ccoLqALvbc"
} at /home/vagrant/carton/metacpan-api/lib/perl5/Search/Elasticsearch/Role/Bulk.pm line 52.
```

According to this post, the type we're using for file.description is limited in size: http://stackoverflow.com/questions/4495791/how-to-match-a-newline-n-in-a-perl-regex

```
         "description" : {
            "type" : "multi_field",
            "fields" : {
               "description" : {
                  "type" : "string",
                  "store" : "yes",
                  "index" : "not_analyzed",
                  "omit_norms" : true,
                  "index_options" : "docs"
               },
               "analyzed" : {
                  "store" : "yes",
                  "type" : "string",
                  "analyzer" : "standard",
                  "include_in_all" : false
               }
            }
         },
```

Basically, what's happening here is that some modules have really huge `=head1 description` sections.

Also, from what I can tell, `multi_field` is going away and being replaced by `string`.  @clintongormley, what would you suggest as a solution to this problem?

**Comment by clintongormley** [comment]
@oalders Lucene Pius a limit on term size ie a 32kB term is meaningless from a search perspective. These should just be dropped and not indexed. Can you punt me to an example document and I'll add the appropriate config

**Comment by oalders** [comment]
@clintongormley Thanks! It's the file.description field http://api.metacpan.org/file/_mapping

You should be able to replicate the error via `t/darkpan.t`.  I'm guessing you'll need to update some deps first.  So, something like:

```
carton install
ES=localhost:9200 prove -l -It/lib t/darkpan.t
```

I think including `t/lib` would be the only difference from what you've been doing.

On a related note, if you remove the `SKIP` block from `t/darkpan.t`, this will allow you to test the code you wrote for `cpanm` lookups, since the test distributions are now being added on-demand to the darkpan.

**Comment by clintongormley** [comment]
This is already fixed with the changes that I have pushed here: https://github.com/CPAN-API/p5-elasticsearch-model/commit/98eb6097b0f037b296f1ef38a5efaf91ff95b8eb

**Comment by oalders** [comment]
@clintongormley thanks! For some reason I didn't see your latest commits.
