### ISSUE TITLE
missing and exists filter on dotted fields don't return results

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/cpan-api#409]
This is probably a bug in my question:

A request to ```/v0/release/_search``` with the following data:

```
{
            "query": {
                "match_all": {}
            },
            "fields" : [ "metadata.resources.repository", "metadata.distribution", "date", "author", "distribution", "name", "metadata.name", "abstract" ],
            "filter" : { "exists" : { "field" : "author" } },
            "sort" : [
                { "date": {"order" : "desc"} }
            ],
            "size" : 1
}
```

works, but if I replace the filter to look for entries with a 'metadata.name'  then I don't get any hits.

My original goal was to use a filter:
```
            "filter" : { "missing" : { "field" : "metadata.resources.repository" } },
```

to list distributions without a repository entry in the metadata.

**Comment by rwstauner** [comment]
It's not well documented, but you can't search the "metadata" structure as there is no mapping defined for it's contents in the elasticsearch index.  I'm not sure why this is (aside from it's obviously dynamic nature), because there are certainly plenty of use cases for it, but currently this is the case.

**Comment by rwstauner** [comment]
However, in this case, "resources" is copied to the root,
so try changing your filter to just `"field": "resources.repository"`.

**Comment by szabgab** [comment]
I tried and

```"filter" : { "missing" : { "field" : "resources.repository" } },```

does not seem to have an impact either, but

```"filter" : { "missing" : { "field" : "resources.repository.type" } },```

has.

In the end I used an "and" filter with 3 missing fields:

https://github.com/szabgab/metacpanjs/commit/26d44c6d035a721b84cbb5cbef0c2d4a64a5f334

That seems to work.

**Comment by szabgab** [comment]
Thanks for your help!

**Comment by rwstauner** [comment]
I wasn't sure that `exists` and `missing` were supposed to work on hashes,
but when i tried it on the command line it seemed to work (at least to some degree).
Maybe it was a coincidence.
I think exists/missing are supposed to be used on scalar fields, so, like you said, ".type" is probably better.
