### ISSUE TITLE
regexp filter does not work

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/cpan-api#412]
I tried using a regexp filter in various way, but it keeps failing.
For example I tried on https://explorer.metacpan.org/
using /search/reverse_dependencies/MetaCPAN-API

```
{
  "filter": {
    "regexp": {
      "name": "CPAN"
    }
  },
  "size": 100
}
```

and it returned 'SearchPhaseExecutionException[Failed to execute phase [query], ...'

Am I doing something wrong?

**Comment by rwstauner** [comment]
Our current version of es is 0.20.2.
The regexp filter was not added until later.

**Comment by szabgab** [comment]
Ah, is there any plan to upgrade?

**Comment by rwstauner** [comment]
Significant work towards upgrading was done recently at the hackathons, but
I cannot predict when it will be finished.

**Comment by ranguard** [comment]
People have run out of time to work on it in the near future... current state can be followed here:

https://github.com/CPAN-API/cpan-api/milestones/Elasticsearch%20upgrade%201.5
