### ISSUE TITLE
Allow searching on metadata as well

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/cpan-api#413]
I was just trying to build a query that would filter based on ```metadata.generated_by``` to show distributions to filter distributions based on their build tool ( Dist::Zilla, EUMM, etc) but neither prefix nor regexp worked and then I remembered the metadata fields are not indexed and they are
not searchable.

Or at least that's what I understood from an earlier report I made #409 

I wonder if it would be possible to index those fields as well, or for now at least the ```metadata.generated_by``` field?

**Comment by ranguard** [comment]
No one stepped forward to do this, closing
