### ISSUE TITLE
Perl-Critic-Compatibility does not have 'provides' in root

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/cpan-api#414]
Other releases have a 'provides' array in the root and a 'provides' hash in metadata,, but 
http://api.metacpan.org/v0/release/Perl-Critic-Compatibility
only has the hash in the metadata. Is this a bug?

**Comment by rwstauner** [comment]
The dist was last indexed before that field was added.

**Comment by rwstauner** [comment]
I have reindexed, and it is there now.

**Comment by szabgab** [comment]
:+1:
