### ISSUE TITLE
Please re-index Net::AMQP and other packages from the same dist

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/cpan-api#424]
Can you re-index the following packages please:

    Net::AMQP
    Net::AMQP::Common
    Net::AMQP::Frame
    Net::AMQP::Frame::Body
    Net::AMQP::Frame::Header
    Net::AMQP::Frame::Heartbeat
    Net::AMQP::Frame::Method
    Net::AMQP::Frame::OOBBody
    Net::AMQP::Frame::OOBHeader
    Net::AMQP::Frame::OOBMethod
    Net::AMQP::Frame::Trace
    Net::AMQP::Protocol
    Net::AMQP::Protocol::Base
    Net::AMQP::Protocol::v0_8

These are listed in 02packages against Net-AMQP-0.06, released by CHIPS, and CHIPS now has permissions for all of those packages. Both 06perms and 02packages have had changes related to this release, long after the release itself happened.

Thanks,
Neil

**Comment by oalders** [comment]
@neilbowers re-indexed.  Let me know if there are still issues. :)

**Comment by neilbowers** [comment]
@oalders it's all good now -- thank you.
