### ISSUE TITLE
Unable to create indexes on ES 2.2.0 

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/cpan-api#443]
On the dev VM...

puppet: es_2.2.0
metacpan-api: stage/lw-mc-03

```
vagrant@metacpan-dev:~/metacpan-api$ ~/bin/metacpan-api-carton-exec ./bin/metacpan mapping
```

Produces:

2016/03/30 20:31:52 I mapping: Putting mapping to ElasticSearch server
[Request] ** [http://127.0.0.1:9200]-[400] [mapper_parsing_exception] Mapping definition for [new] has unsupported parameters:  [ignore_above : 2048], called from sub Search::Elasticsearch::Transport::perform_request at /home/vagrant/carton/metacpan-api/lib/perl5/ElasticSearchX/Model/Role.pm line 51. With vars: {'body' => {'error' => {'reason' => 'Mapping definition for [new] has unsupported parameters:  [ignore_above : 2048]','root_cause' => [{'type' => 'mapper_parsing_exception','reason' => 'Mapping definition for [new] has unsupported parameters:  [ignore_above : 2048]'}],'type' => 'mapper_parsing_exception'},'status' => 400},'request' => {'path' => '/cpan_v1/distribution/_mapping','qs' => {},'ignore' => [],'serialize' => 'std','body' => {'distribution' => {'dynamic' => \0,'properties' => {'bugs' => {'fielddata' => {'format' => 'disabled'},'type' => 'object','dynamic' => \1,'properties' => {'new' => {'type' => 'integer','ignore_above' => 2048,'index' => 'not_analyzed','doc_values' => \1,'store' => 'yes'},'resolved' => {'ignore_above' => 2048,'type' => 'integer','store' => 'yes','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'index' => 'not_analyzed'},'stalled' => {'type' => 'integer','ignore_above' => 2048,'index' => 'not_analyzed','store' => 'yes','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'}},'closed' => {'type' => 'integer','ignore_above' => 2048,'index' => 'not_analyzed','store' => 'yes','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'}},'patched' => {'index' => 'not_analyzed','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'store' => 'yes','type' => 'integer','ignore_above' => 2048},'open' => {'ignore_above' => 2048,'type' => 'integer','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'store' => 'yes','index' => 'not_analyzed'},'type' => {'index' => 'not_analyzed','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'store' => 'yes','type' => 'string','ignore_above' => 2048},'rejected' => {'store' => 'yes','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'index' => 'not_analyzed','ignore_above' => 2048,'type' => 'integer'},'active' => {'type' => 'integer','ignore_above' => 2048,'index' => 'not_analyzed','store' => 'yes','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'}},'source' => {'type' => 'string','ignore_above' => 2048,'index' => 'not_analyzed','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'store' => 'yes'}}},'name' => {'type' => 'string','ignore_above' => 2048,'index' => 'not_analyzed','doc_values' => $VAR1->{'request'}{'body'}{'distribution'}{'properties'}{'bugs'}{'properties'}{'new'}{'doc_values'},'store' => 'yes'}}}},'method' => 'PUT','mime_type' => 'application/json'},'status_code' => 400}

**Comment by mickeyn** [comment]
As a side note (I missed it on https://github.com/CPAN-API/cpan-api/issues/408, but I'm sure you are well aware), a road blocker I find is the missing adaptation of `ElasticSearchX::Model` to ES2+ (even some 1.X versions are not fully supported - e.g. `delete_by_query` is not supported in late ES or Serach::Elasticsearch versions).

**Comment by oalders** [comment]
I think `ElasticSearchX::Model` is the problem here as well.  #408 was created before 2.x was released, I believe, so we weren't even thinking in terms of that release yet.  :)

I did not know about `delete_by_query` not being supported.  Is that a problem?

**Comment by mickeyn** [comment]
I only encountered it in the ratings indexing on 1.7.5
(I think I can can bypass that one with query and then delete)

**Comment by mickeyn** [comment]
One correction: it was deprecated in ES 1.5.3 and removed in 2.0
The reason it bit me is that it's not supported in `Search::Elasticsearch 2.00`

**Comment by ranguard** [comment]
Strangely `ignore_above` does seems to be still valid:

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/ignore-above.html

**Comment by mickeyn** [comment]
Not sure if this will solve that problem yet (I haven't yet tested the indexing, will do next), but on a related note I took a shot at updating `ElasticSearchX::Model` to work with `ES 2+ (2.3)`.
PR: https://github.com/CPAN-API/p5-elasticsearch-model/pull/1

**Comment by mickeyn** [comment]
@ranguard `ignore_above` (esp. to such length) doesn't seem to make sense with `integer` fields as in this error.
I see that limiting it to `string` types does help moving on to the next mapping issue.
I'll patch https://github.com/CPAN-API/p5-elasticsearch-model/pull/1 accordingly.

**Comment by oalders** [comment]
I believe this is now resolved.
