### ISSUE TITLE
Stop using lazy_build

### ISSUE THREAD

**Issue by oalders** [CPAN-API/cpan-api#447]
```
bash-3.2$ git grep lazy_build | wc -l
      33
```

Replace with `ro` attributes which have explicit builders.

**Comment by oalders** [comment]
Or use `MooseX::AttributeShortcuts`

**Comment by mickeyn** [comment]
Wouldn't that be replacing one magic with another that hides options? :)
I suggest having explicit list of options for each attribute ( `lazy` & `builder` if we need them)

for example, 15 of those 33 are marked as `required => 1` which doesn't make sense to me if we trust the builders to populate them (we hardly, if at all use any of the `clearer`s  that lazy_build creates, so why not just use `default` if it's `ro` anyway?).

**Comment by mickeyn** [comment]
BTW, in `lib/MetaCPAN/Document/File.pm`:
`has slop` has both `is => 'ro'` and `is => 'rw'` in the code,
i'm guessing it was meant to be `rw` as a value setting is called from `_build_pod_lines` but I would make it `ro` with an explicit `writer` for that specific use-case.

**Comment by oalders** [comment]
@shadowcat-mst had suggested `MooseX::AttributeShortcuts` and made some good points for using it.  I'm not too fussy about how we do it, but the accessors need to be cleaned up.

I think a lot of this stuff was probably done in a hurry and once it "just worked" it never really got a close look.  Also, it was done before `lazy_build` was discouraged.

Making as many accessors as possible `ro` would be great. :)

**Comment by mickeyn** [comment]
I actually, chatted before with @stevan about it, the "replacing one magic with another" sentence should be credited to him :) 

In any case, I'll look into making those corrections as part of the `mi/es2` branch (any objections?)

**Comment by stevan** [comment]
@oalders I will remind you that @shadowcat-mst was the person who came up with `lazy_build` in the first place, so clearly his suggestions are highly suspect to say the least.

**Comment by shadowcat-mst** [comment]
On Fri, Apr 15, 2016 at 07:54:18AM -0700, Stevan Little wrote:
> @oalders I will remind you that @shadowcat-mst was the person who came up with `lazy_build` in the first place, so clearly his suggestions are highly suspect to say the least.

And then you let a coke fueled madman patch it into Moose when I'd designed
it specifically for caching stuff and wasn't happy with the design yet.

is => 'lazy' would be the version two that I'm actually relatively happy
with :)

-- 
Matt S Trout - Shadowcat Systems - Perl consulting with a commit bit and a clue

http://shadowcat.co.uk/blog/matt-s-trout/   http://twitter.com/shadowcat_mst/

Email me now on mst (at) shadowcat.co.uk and let's chat about how our CPAN
commercial support, training and consultancy packages could help your team.

**Comment by mickeyn** [comment]
Created #451 to fix it on the ES2 branch.

Some of the attributes probably shouldn't be lazy as they are accessed immediately after the object creation (so maybe just set them in BUILD?). having too many, esp. triggering each other are exposing us to deep recursion issues.

**Comment by shadowcat-mst** [comment]
On Sun, Apr 17, 2016 at 03:44:28AM -0700, Mickey wrote:
> Created #451 to fix it on the ES2 branch.
> 
> Some of the attributes probably shouldn't be lazy as they are accessed immediately after the object creation (so maybe just set them in BUILD?). having too many, esp. triggering each other are exposing us to deep recursion issues.

Setting attributes in BUILD is a massive antipattern, avoid that if at all
possible (or if you do, make sure to use 'is => 'rwp'' or the moral equivalent
thereof).

If you're exposed to deep recursion issues by too many triggers, you needed
fewer triggers.

De-lazying attributes to hide other design problems is an error, but if you
have specific pieces of code to point at, I'd be happy to make more concrete
suggestions.

-- 
Matt S Trout - Shadowcat Systems - Perl consulting with a commit bit and a clue

http://shadowcat.co.uk/blog/matt-s-trout/   http://twitter.com/shadowcat_mst/

Email me now on mst (at) shadowcat.co.uk and let's chat about how our CPAN
commercial support, training and consultancy packages could help your team.

**Comment by mickeyn** [comment]
@shadowcat-mst thanks for the advice, much appreciated. I'll have dig into the logic a bit more first.
