### ISSUE TITLE
Indexing under es 2 - a step closer.. but...

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/cpan-api#450]
@oalders @mickeyn 

### Good news:

mi/es branches now deployed on the liquid web cluster and

mappings work

### Bad news (though some data is going into the index, so not all bad):

```sh
metacpan@lw-mc-03:~/metacpan-api$  ~/bin/metacpan-api-carton-exec ./bin/metacpan release /home/metacpan/CPAN/authors/id/L/LL/LLAP/
```
2016/04/16 20:59:57 I release: Looking for archives in /home/metacpan/CPAN/authors/id/L/LL/LLAP/
2016/04/16 20:59:57 I release: 146 archives found
2016/04/16 21:00:01 I release: Processing /home/metacpan/CPAN/authors/id/L/LL/LLAP/Data-Pageset-0.02.tar.gz
2016/04/16 21:00:01 I release: Processing /home/metacpan/CPAN/authors/id/L/LL/LLAP/Acme-Test-Pr0n-0.01.tar.gz
2016/04/16 21:00:01 I release: Processing /home/metacpan/CPAN/authors/id/L/LL/LLAP/Data-Pageset-0.03.tar.gz
Deep recursion on subroutine "MetaCPAN::Model::Release::files" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 472.
Deep recursion on subroutine "MetaCPAN::Model::Release::_build_files" at reader MetaCPAN::Model::Release::files (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 63) line 8.
Deep recursion on subroutine "File::Find::find" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 334.
Deep recursion on subroutine "File::Find::_find_opt" at /opt/perl-5.18.2/lib/5.18.2/File/Find.pm line 1079.
Deep recursion on subroutine "File::Find::_find_dir" at /opt/perl-5.18.2/lib/5.18.2/File/Find.pm line 578.
Deep recursion on subroutine "MetaCPAN::Model::Release::document" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 312.
Deep recursion on subroutine "MetaCPAN::Model::Release::_build_document" at reader MetaCPAN::Model::Release::document (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 50) line 8.
Deep recursion on subroutine "MetaCPAN::Model::Release::files" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 472.
Deep recursion on subroutine "MetaCPAN::Model::Release::_build_files" at reader MetaCPAN::Model::Release::files (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 63) line 8.
Deep recursion on subroutine "File::Find::find" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 334.
Deep recursion on subroutine "File::Find::_find_opt" at /opt/perl-5.18.2/lib/5.18.2/File/Find.pm line 1079.
Deep recursion on subroutine "File::Find::_find_dir" at /opt/perl-5.18.2/lib/5.18.2/File/Find.pm line 578.
Deep recursion on subroutine "MetaCPAN::Model::Release::document" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 312.
Deep recursion on subroutine "MetaCPAN::Model::Release::_build_document" at reader MetaCPAN::Model::Release::document (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 50) line 8.
Deep recursion on subroutine "MetaCPAN::Model::Release::modules" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 209.
Deep recursion on anonymous subroutine at reader MetaCPAN::Model::Release::modules (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 102) line 6.
Deep recursion on subroutine "MetaCPAN::Model::Release::_modules_from_files" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 99.
Deep recursion on subroutine "MetaCPAN::Model::Release::modules" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 209.
Deep recursion on anonymous subroutine at reader MetaCPAN::Model::Release::modules (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 102) line 6.
Deep recursion on subroutine "MetaCPAN::Model::Release::_modules_from_files" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 99.
Deep recursion on subroutine "MetaCPAN::Model::Release::files" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 472.
Deep recursion on subroutine "MetaCPAN::Model::Release::_build_files" at reader MetaCPAN::Model::Release::files (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 63) line 8.
Deep recursion on subroutine "File::Find::find" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 334.
Deep recursion on subroutine "File::Find::_find_opt" at /opt/perl-5.18.2/lib/5.18.2/File/Find.pm line 1079.
Deep recursion on subroutine "File::Find::_find_dir" at /opt/perl-5.18.2/lib/5.18.2/File/Find.pm line 578.
Deep recursion on subroutine "MetaCPAN::Model::Release::document" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 312.
Deep recursion on subroutine "MetaCPAN::Model::Release::_build_document" at reader MetaCPAN::Model::Release::document (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 50) line 8.
Deep recursion on subroutine "MetaCPAN::Model::Release::modules" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 209.
Deep recursion on anonymous subroutine at reader MetaCPAN::Model::Release::modules (defined at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 102) line 6.
Deep recursion on subroutine "MetaCPAN::Model::Release::_modules_from_files" at /home/metacpan/metacpan-api/bin/../lib/MetaCPAN/Model/Release.pm line 99.

**Comment by mickeyn** [comment]
I noticed those deep recursion errors on my VM.
They started after the merge from master.

**Comment by mickeyn** [comment]
I see it's fixed now by @oalders. thanks.

**Comment by oalders** [comment]
Yeah, sorry for my sloppy work. ;)
