### ISSUE TITLE
Run minion_queue on all lw servers

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/cpan-api#452]
Update config to have the DSN connection use: 50.28.18.168

After that run puppet on lw-mc-01, 02 and 03

**Comment by oalders** [comment]
The code changes are in https://github.com/CPAN-API/cpan-api/commit/6d610051d25d3a516d2a0bc7e14f95ebde22b5a0  I was going to add this to a `metacpan_server_local.conf` on each box, but I see that is managed by puppet.  So, we need to add this line to `metacpan_server_local.conf` on each `lw` box:

minion_dsn = postgresql://@50.28.18.168/minion_queue

@ranguard can I bounce this back to you?
