### ISSUE TITLE
Tickets _set_bugs doesn't seem to work

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/cpan-api#455]
In `index_bug_summary()` _set_bugs isn't adding values (though debug seems to suggest there are values to submit).

https://github.com/CPAN-API/cpan-api/blob/mi/es2/lib/MetaCPAN/Script/Tickets.pm#L106

***Comment out github in the source() otherwise it takes ages***

To run script:
```
vagrant@metacpan-dev:~/metacpan-api$ ~/bin/metacpan-api-carton-exec bin/metacpan tickets
```

Then check `curl localhost:9200/cpan_v1/distibution/_search` - there should be `bugs` not just `name` key.

**Comment by oalders** [comment]
We're seeing similar issues with the cpanratings test script.

**Comment by mickeyn** [comment]
Is this issue still relevant? I can't recreate it for `tickets`

I do, however, suspect this was a result of how we use `bulk` calls and we may still have some broken scripts.

**Comment by ranguard** [comment]
Closing - will open again if needed!
