### ISSUE TITLE
Check if mirror sync is stuck

### ISSUE THREAD

**Issue by oalders** [CPAN-API/cpan-api#463]
>  meta::cpan's mirror list is out-of-date :

>   https://metacpan.org/mirrors

> Did the 'refresh mechanism' get stuck ?

**Comment by ranguard** [comment]
bm-mc-01 and 02 both have the latest mirrors.json file and I don't see any errors running it.

The page show `370 results` - which matches our new ES env as well.

I'm a bit confused at the mirrors.json only has `242` `continent or country` values as our front end groups the results by these keys, so maybe we're just not displaying it correctly?

**Comment by oalders** [comment]
Haven't looked closely at this part of the code yet, so can't currently be helpful. :(

**Comment by ranguard** [comment]
Fairly sure it is because we do not delete the old entries
