### ISSUE TITLE
[mi/es2] tests issue with test_psgi

### ISSUE THREAD

**Issue by mickeyn** [CPAN-API/cpan-api#469]
in some tests we run `GET <path>` in `test_psgi` and get `404`s while `curl http://localhost:5000/<path>` work.

examples:
`./t/script/river.t L43` vs `curl http://localhost:5000/distribution/System-Command`
`./t/server/controller/author.t L18` vs `curl http://localhost:5000/author`
`./t/server/controller/file.t L19` vs `curl http://localhost:5000/file/DOY/Moose-0.01/lib/Moose.pm`
`./t/server/controller/mirror.t L17` vs `curl http://localhost:5000/mirror/_search?q=*`
(it happens in several more, I guess they all have the same test setup so it's just a repeating issue)

**Comment by oalders** [comment]
From what I can tell, when run via the test suite, `GET /distribution/System-Command` fires `MetaCPAN::Server::Controller::Root::default()` rather than `MetaCPAN::Server::Controller::get()`.  Not sure why that is.  

@shadowcat-mst any hints?

**Comment by oalders** [comment]
Closed via e4c856e4f4
