### ISSUE TITLE
indexing issues from the minion queue

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/cpan-api#477]
From:

/var/log/starman/metacpan-api

tail -1000 minion_queue-error.log | grep unini | sort | uniq -c

     39 Use of uninitialized value in join or string at lib/MetaCPAN/Document/File.pm line 929.
      1 Use of uninitialized value in string eq at lib/MetaCPAN/Document/File.pm
    608 Use of uninitialized value in string eq at lib/MetaCPAN/Document/File.pm line 908.
    106 Use of uninitialized value in string eq at lib/MetaCPAN/Document/File.pm line 912.
     15 Use of uninitialized value $pauseid in sprintf at lib/MetaCPAN/Util.pm line 59.

**Comment by mickeyn** [comment]
the log (`minion_queue-error.log`) doesn't seem to provide enough info to help recreate the issue for debugging.
how can we associate these warnings with the processed tarballs that generated them?
